### PR TITLE
-C cmake.args issue

### PR DESCRIPTION
**Pull request by negativenagesh**
### In requirements.txt

1. The arguments cmake.args="-DLLAMA_BLAS=ON" are meant for cmake during the package building process, but pip does not recognize -C as a valid option.

so I commented this line in requirements.txt - 

`llama_cpp_python == 0.2.78 -C cmake.args="-DLLAMA_BLAS=ON"`

and added only

`llama_cpp_python == 0.2.78`

Check out -C, why and where its used. [Link](https://cmake.org/cmake/help/latest/manual/cmake.1.html)
-C
Pre-load a script to populate the cache. When CMake is first run in an empty build tree, it creates a CMakeCache.txt file and populates it with customizable settings for the project. This option may be used to specify a file from which to load cache entries before the first pass through the project's CMake listfiles. The loaded entries take priority over the project's default values. The given file should be a CMake script containing [set()](https://cmake.org/cmake/help/latest/command/set.html#command:set) commands that use the CACHE option, not a cache-format file.

2. or else remove this line - llama_cpp_python == 0.2.78 -C cmake.args="-DLLAMA_BLAS=ON" from requirements.txt and install this seperately - 

 `pip install llama_cpp_python==0.2.78 --config-settings cmake-args="-DLLAMA_BLAS=ON"`

### CODE REVIEW

**Comment by MaartenGr** [comment]
Thank you for sharing this. If I'm not mistaken, pip does seem to support -C according to its [official documentation](https://pip.pypa.io/en/latest/cli/pip_install/#cmdoption-C). Likewise, the [official documentation](https://github.com/abetlen/llama-cpp-python?tab=readme-ov-file#installation-configuration) of `llama-cpp-python` also suggests this method. 

It might have something to do with your pip version although I cannot be sure.

**Comment by negativenagesh** [comment]
you are right pip does not support -C according to its [official documentation](https://pip.pypa.io/en/latest/cli/pip_install/#cmdoption-C),

 when someone tries to do `pip install -r requirements.txt` from your repo, it gives error because of this - `llama_cpp_python == 0.2.78 -C cmake.args="-DLLAMA_BLAS=ON"` in your requirements.txt,

So i created this pull request to correct that part in requirements.txt, please check once again, what i did and files changed,
instead of `llama_cpp_python == 0.2.78 -C cmake.args="-DLLAMA_BLAS=ON"` i have commented this and added only `llama_cpp_python == 0.2.78` 

or I will simply remove this line `llama_cpp_python == 0.2.78 -C cmake.args="-DLLAMA_BLAS=ON"` from requirements.txt

and install seperately ``pip install llama_cpp_python==0.2.78 --config-settings cmake-args="-DLLAMA_BLAS=ON"`` which wont give any error,

So tell me what i should do with it, i will correct and commit again?, im waiting for your command..

**Comment by MaartenGr** [comment]
> you are right pip does not support -C according to its [official documentation](https://pip.pypa.io/en/latest/cli/pip_install/#cmdoption-C)

It **does** support it right? The official documentation seems to mention that and whenever I install from the requirements.txt, I get no issues at all. Could you demonstrate what is going wrong for you?

**Comment by negativenagesh** [comment]
https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/issues/6

this above issue was raised on your repo, for the same i mentioned above regarding `llama_cpp_python == 0.2.78 -C cmake.args="-DLLAMA_BLAS=ON` and I gave him the solution, and you closed the issue, so i changed the requirements.txt and pulled request, check once.. the files changed. So I commented this code which was giving issue for some of them, and changed it to `llama_cpp_python == 0.2.78` which wont give any error for anyone.

image

**Comment by MaartenGr** [comment]
Don't get me wrong, I think I understand what you are saying. However, I do not run into that issue on my local machine. As such, it seems that the issue might also be the version of pip that you are using. The official documentation of both pip and llama-cpp-python mentions the possibility of using the -C tag.

Therefore, this might also mean that if you update pip to the latest version, you can run the requirements.txt without any issue (as is the case for me). The -C tag is necessary to run models with GPU and if I'm not mistaken relates to [pip](https://pip.pypa.io/en/latest/cli/pip_install/#cmdoption-C) and scikit-build-core. I believe that [this comment](https://github.com/abetlen/llama-cpp-python/issues/989#issuecomment-2038194139) on the official llama-cpp-python repository explains this well. 

As a result, if we were to remove that tag, that would inhibit the expected functionality of the code (which is to run on GPU). That means that updating the requirements.txt would be insufficient as additional instructions are needed for llama-cpp-python specifically. 

Instead, I would propose adding a comment in the installation that we need the latest version of pip instead as that should fix this issue and follows the recommendations of the llama-cpp-python repository (which we want to follow as much as possible).

**Comment by MaartenGr** [comment]
I'm not sure whether it is needed at that location or rather in the `.setup` folder with a minor comment. It might be best to add it as a tip the same way it is done [here](https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/tree/main/.setup).

**Comment by negativenagesh** [comment]
Okay I will add a tip above that line in requirements.txt

**Comment by negativenagesh** [comment]
> I'm not sure whether it is needed at that location or rather in the `.setup` folder with a minor comment. It might be best to add it as a tip the same way it is done [here](https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/tree/main/.setup).

@MaartenGr I have added a Tip as you said here - https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/pull/8#issuecomment-2373548019 in [.setup/conda/README.md](https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/blob/main/.setup/conda/README.md) please check and tell me if anything is required

**Comment by MaartenGr** [comment]
@negativenagesh Could you remove all changes you made to the requirements.txt? I think we only need the comment in the readme and nothing more.

**Comment by negativenagesh** [comment]
> @negativenagesh Could you remove all changes you made to the requirements.txt? I think we only need the comment in the readme and nothing more.

@MaartenGr 

Done--> https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/pull/8/commits/9a1c85e61ae0a2bc98fa45a4984018502fa43836

removed all changes from requirements.txt

**Comment by MaartenGr** [comment]
@negativenagesh Awesome, looks good to me! Thanks for the PR.

**Comment by negativenagesh** [comment]
> @negativenagesh Awesome, looks good to me! Thanks for the PR.

Thank you for your time 🙏

**Pull request merged**
